# Copyright (c) 2025 Fantom Foundation
#
# Use of this software is governed by the Business Source License included
# in the LICENSE file and at fantom.foundation/bsl11.
#
# Change Date: 2028-4-16
#
# On the date above, in accordance with the Business Source License, use of
# this software will be governed by the GNU Lesser General Public License v3.

version: 0.4.5-rc1#{build}
image: Visual Studio 2017

build: off

clone_folder: c:\gopath\src\github.com\0xsoniclabs\consensus

environment:
  PATH: C:\gopath\bin;C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin;C:\PROGRA~1\Git\bin;C:\PROGRA~1\Git\usr\bin\;C:\ProgramData\chocolatey\bin;$(PATH)
  GOPATH: c:\gopath
  GO111MODULE: on

stack: go 1.13

init:
  - choco install make mingw

cache:
  - C:\usr
  - C:\ProgramData\chocolatey

before_test:
  - ps: Set-NetFirewallProfile -All -Enabled False
  - ps: Disable-NetFirewallRule -All

test_script:
  - go test -v ./...
